language: swift

matrix:
  include:
    - os: linux
      dist: trusty
      language: generic
      env: SWIFT_VERSION=3.1.1

    - os: linux
      dist: trusty
      language: generic
      env: SWIFT_VERSION=4.1.3

    - os: linux
      dist: trusty
      language: generic
      env: SWIFT_VERSION=4.2

    - os: osx
      osx_image: xcode8.3
      env: SWIFT_VERSION=3.1.1

    - os: osx
      osx_image: xcode9
      env: SWIFT_VERSION=3.2

    - os: osx
      osx_image: xcode10

before_install:
  - chmod u+x Tests/install-swift.sh
  - . Tests/install-swift.sh

script:
  - /bin/bash Tests/test-script.sh
